# Generated by Django 3.2.3 on 2021-06-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GSApp', '0002_gspdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSpdf2img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_2_img', models.FileField(upload_to='pdf2img')),
            ],
        ),
        migrations.DeleteModel(
            name='GSModel',
        ),
    ]
