# Generated by Django 3.2.3 on 2021-06-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GSApp', '0003_auto_20210616_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='gspdf2img',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='pdf2img/images'),
        ),
    ]
